#!/usr/bin/env bash
# Changes localhost and facebook.com IP associations in hosts file.

grep -v -E 'localhost|facebook.com' /etc/hosts > /tmp/hosts
cat /tmp/hosts > /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
